export const linkMappings = [
       
    { subPath: "/Mrv/create-tenant", mainPath: "/Mrv/tenants" },
    { subPath: "/Mrv/edit-tenant", mainPath: "/Mrv/tenants" },
    { subPath: "/Mrv/create-organization", mainPath: "/Mrv/organizations" },
    { subPath: "/Mrv/edit-organization", mainPath: "/Mrv/organizations" },
    { subPath: "/Mrv/view-organization", mainPath: "/Mrv/organizations" },
    { subPath: "/Mrv/create-role", mainPath: "/Mrv/roles" },
    { subPath: "/Mrv/edit-role", mainPath: "/Mrv/roles" },
    { subPath: "/Mrv/view-role", mainPath: "/Mrv/roles" },
    { subPath: "/Mrv/create-user", mainPath: "/Mrv/users" },
    { subPath: "/Mrv/edit-user", mainPath: "/Mrv/users" },
    { subPath: "/Mrv/view-user", mainPath: "/Mrv/users" },
    { subPath: "/Mrv/fuelmanager", mainPath: "/Mrv/fuelmanager" },
    { subPath: '/Mrv/view-emission/:power', mainPath: '/Mrv/view-emission/:power'},
    { subPath: '/Mrv/add-facility/:power', mainPath: '/Mrv/add-facility/:power' },
    { subPath: '/Mrv/view-emission/:petroleum', mainPath: '/Mrv/view-emission/:petroleum'},
    { subPath: '/Mrv/add-facility/:petroleum', mainPath: '/Mrv/add-facility/:petroleum' },
    { subPath: '/Mrv/view-emission/:construction', mainPath: '/Mrv/view-emission/:construction'},
    { subPath: '/Mrv/add-facility/:construction', mainPath: '/Mrv/add-facility/:construction' },
    { subPath: '/Mrv/transportation/:aviation', mainPath: '/Mrv/transportation/:aviation'},
    { subPath: '/Mrv/add-transportation/:aviation', mainPath: '/Mrv/add-transportation/:aviation' },
    { subPath: '/Mrv/transportation/:road', mainPath: '/Mrv/transportation/:road'},
    { subPath: '/Mrv/add-transportation/:road', mainPath: '/Mrv/add-transportation/:road' },
    { subPath: '/Mrv/transportation/:navigation', mainPath: '/Mrv/transportation/:navigation'},
    { subPath: '/Mrv/add-transportation/:navigation', mainPath: '/Mrv/add-transportation/:navigation' },
    { subPath: '/Mrv/emission-data/:power', mainPath: '/Mrv/emission-data/:power'},
    { subPath: '/Mrv/emission-data/:petroleum', mainPath: '/Mrv/emission-data/:petroleum'},
    { subPath: '/Mrv/emission-data/:construction', mainPath: '/Mrv/emission-data/:construction'},
  ];